version: "3.8"
services:
  sv-node:
    build: .
    container_name: cont-node
    # command: sh -c "yarn install && yarn run:dev"
    ports:
      - 8002:8000
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - nw-backend
    environment:
      MYSQL_HOST: MYSQL_HOST
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_DB: MYSQL_DB
  sv-mysql:
    image: mysql
    container_name: cont-mysql
    ports:
      - 3308:3306
    volumes:
      - vol-mysql:/var/lib/mysql
    networks:
      - nw-backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: DBInstanceMySQL
networks:
  nw-backend:
    name: todo-app-network
volumes:
  vol-mysql:
